"""Constants for the Warframe Stats integration."""

DOMAIN = "warframe"

CONF_WORLDSTATES = "worldstates"
CONF_PROFILES = "profiles"
CONF_STATIC_ITEMS = "static_items"

CONF_ALERTS = "alerts"
CONF_ARCHON_HUNT = "archon_hunt"
CONF_OPEN_WORLDS = "open_worlds"
CONF_RELAY_EVENTS = "relay_events"
CONF_DEEP_ARCHIMEDEA = "deep_archimedea"
CONF_EARTH_TIME = "earth_time"
CONF_EVENTS = "events"
CONF_FISSURES = "fissures"
CONF_INVASIONS = "invasions"
CONF_SORTIES = "sorties"
CONF_STEEL_PATH = "steel_path"
CONF_VOID_TRADER = "void_trader"
CONF_VARZIA = "varzia"

CONF_USERNAMES = "usernames"
CONF_TOTAL_ABILITIES_USED = "total_abilities_used"
CONF_TOTAL_ENEMIES_KILLED = "total_enemies_killed"
CONF_MOST_SCANS = "most_scans"
CONF_MOST_USED_WARFRAME = "most_used_warframe"
CONF_MOST_USED_PRIMARY = "most_used_primary"
CONF_MOST_USED_SECONDARY = "most_used_seondary"
CONF_MOST_USED_MELEE = "most_used_melee"
CONF_MOST_USED_COMPANION = "most_used_companion"
CONF_CREDITS = "credits"
CONF_RANK = "rank"
CONF_DEATHS = "death"
CONF_TIME_PLAYED = "time_played"
CONF_STAR_CHART_COMPLETION = "star_chart_completion"

CONF_TOTAL_ITEMS = "total_items"
CONF_TOTAL_PRIME_ITEMS = "total_prime_items"
CONF_NEWEST_WARFRAME = "newest_warframe"

URL_BASE = "https://api.warframestat.us/"
URL_TRANSLATION_SORTIES_ENDPOINT = "sortie"
URL_TRANSLATION_FACTIONS_ENDPOINT = "factions"
URL_TRANSLATION_FISSURE_MODIFERS_ENDPOINT = "fissureModifiers"
URL_TRANSLATION_SOL_NODES_ENDPOINT = "solNodes"
URL_TRANSLATION_SYNDICATES_ENDPOINT = "syndicates"
URL_TRANSLATION_MISSION_TYPES_ENDPOINT = "missionTypes"
URL_TRANSLATION_OTHER_ENDPOINT = "languages"

URL_WORLD_STATE_ENDPOINT = "pc"
URL_PRE_PROFILE_ENDPOINT = "profile/"
URL_STATS_ENDPOINT = "/stats"
URL_STATIC_ITEM_ENDPOINT = "warframes"